apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: image-pvc
      containers:
        - name: todo-app
          image: PROJECT/IMAGE
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 3000
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 3000
          env:
            - name: NATS_URL
              value: nats://my-nats:4222
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-database-password
                  key: POSTGRES_PASSWORD
            - name: USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: user
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: host
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: port
            - name: DATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: database
          volumeMounts:
            - name: shared-volume
              mountPath: /usr/src/app/img
          resources:
            limits:
              memory: 500Mi
              cpu: "0.5"
