resources:
- ../../base

patches:
- path: nats-deployment.yaml

images:
- name: PROJECT/IMAGE
  newName: hzd454/todo-app
  newTag: 853af2c0f47d5c798afefba540d289c7bf22a6a0
- name: PROJECT/NATS_IMAGE
  newName: hzd454/nats-broadcaster
  newTag: 87dd3b65c30759d47d7a70a999928bbc53ec4d37
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
