resources:
  - ../../base

patches:
  - path: nats-deployment.yaml

namePrefix: staging-

images:
  - name: PROJECT/NATS_IMAGE
    newName: hzd454/nats-broadcaster
    newTag: a746ec864855874802963cecaa240623fb770a02
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
