resources:
- ../../base

patches:
- path: nats-deployment.yaml

namePrefix: staging-

images:
- name: PROJECT/IMAGE
  newName: hzd454/todo-app
  newTag: ac13eb62b49c89ed455d0d014d5794abe2684f83
- name: PROJECT/NATS_IMAGE
  newName: hzd454/nats-broadcaster
  newTag: c8b276769c9d97de619a0f77443005e7bdf63ec2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
