apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  init-db.sql: |
    CREATE DATABASE mydb;
    \c mydb
    CREATE TABLE todo (id SERIAL PRIMARY KEY, title TEXT, done BOOLEAN);
    INSERT INTO todo(title, done) VALUES ('feed the dog', false);
    INSERT INTO todo(title, done) VALUES ('feed the cat', false);
